version: "3.7"
services:
  postgres:
    image: postgres:9.6.6-alpine
    ports:
      - 5430:5432
    volumes:
      - ./docker-support/postgres-db-rafantasy:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=rafantasy
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
